# fly.toml app configuration file generated for albatross-aurora-1 on 2023-11-20T17:57:40-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "albatross-aurora-1"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  # The build context and the Dockerfile are uploaded to a fly.io builder and built there.

[env]
  RUST_BACKTRACE = "1"

  # The following environment variables should be set with fly.io's secret functionality, e.g.:
  #
  # fly secrets set RPC_USERNAME="<username>"
  # fly secrets set RPC_PASSWORD="<password>"
  #
  # Validator Identity, can NOT be rotated, related "offline" private key required for (un)registering validator.
  # fly secrets set VALIDATOR_ADDRESS="<address>"
  #
  # Can be any BLS secret key, can be rotated, "online"
  # fly secrets set VOTING_KEY="<voting-key>"
  #
  # Can be any private key, can be rotated, "online"
  # fly secrets set SIGNING_KEY="<signing-key>"

[[mounts]]
  source = "albatross_data"
  destination = "/data"
  processes = ["app"]

# Node networking
[[services]]
  protocol = "tcp"
  internal_port = 8443
  processes = ["app"]

  [[services.ports]]
    port = 443
    handlers = ["tls"]

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "2s"
    grace_period = "10s"

# RPC
[[services]]
  protocol = "tcp"
  internal_port = 8648
  processes = ["app"]

  [[services.ports]]
    port = 80 # Insecure

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "2s"
    grace_period = "10s"

# Metrics server
[[metrics]]
  port = 9100
  path = "/metrics"
